name: CI Pipeline - Maquina de Cafe TDD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maquina-cafe

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Compilar proyecto
        run: mvn compile

      - name: Ejecutar pruebas TDD
        run: mvn test